name: CID
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: checkout #utilizado para obter o código que esta na "raiz" do projeto, sem ele o comando de execução não encontraria um código para executar
      uses: actions/checkout@v6.0.0 #Actions/checkout é uma ação oficial do github 
      
    - name: Login no Docker Hub
      uses: docker/login-action@v3 #docker/login é uma ação oficial do github 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} #${{ }} é uma expressão do github actions
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Branche de trabaho
      run: echo "Pull realizada através da branche" >> $GITHUB_REF_NAME
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: | 
          thalysluuan/pipeline:v${{ github.run_number }}
          thalysluuan/pipeline:latest
