name: CID-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: checkout #utilizado para obter o código que esta na "raiz" do projeto, sem ele o comando de execução não encontraria um código para executar
      uses: actions/checkout@v6.0.0 #Actions/checkout é uma ação oficial do github 
    - name: Login no Docker Hub
      uses: docker/login-action@v3 #docker/login é uma ação oficial do github 
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }} #${{ }} é uma expressão do github actions
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
